### ISSUE TITLE
Output vagrant output by default

### ISSUE THREAD

**Issue by matti** [kontena/kontena-plugin-vagrant#25]
To catch things like: http://stackoverflow.com/a/40501585

So instead of silencing the output here be more verbose:

https://github.com/kontena/kontena-plugin-vagrant/blob/master/lib/kontena/machine/vagrant/master_provisioner.rb#L59

**Comment by matti** [comment]
can be closed now?

**Comment by SpComb** [comment]
Yes, the `Fixes ...` syntax in the PR needs to be in front of both issues names :)
