### ISSUE TITLE
kontena vagrant master create systemd unit times out on Docker image pull

### ISSUE THREAD

**Issue by stvndall** [kontena/kontena-plugin-vagrant#40]
I don't know if this should be here instead?
[issue on main kontena repo](https://github.com/kontena/kontena/issues/2413)

**Comment by SpComb** [comment]
See https://github.com/kontena/kontena/issues/1960, the systemd service units have an implicit `DefaultTimeoutStartSec=90s` for things like `ExecStartPre=/usr/bin/docker pull mongo:3.0`... with a slow internet connection where pulling the docker image takes more than 1.5 minutes, booting up the vagrant node will enter a systemd service restart loop, where it aborts the docker image pull every 90s, and it never completes.
